version: '3'
services:
  app:
    image: clean557/laratm:${IMAGE_VER}
    container_name: laratm
    restart: unless-stopped
    tty: true
    volumes:
      - .env:/var/www/html.env
    networks:
      - laratm-net

  nginx:
    image: clean557/laratm-apache2:${IMAGE_VER}
    container_name: apache2
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laratm-net

#Docker Networks
networks:
  laratm-net:
    driver: bridge
