
name: Deploy Application

on:
  push:
    branches: ["balance-feature"]

jobs:
  build:
    environment: staging
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/laravel.Dockerfile
          push: true
          tags: clean557/laratm:${{ github.run_number }}

      - name: Build and push nginx image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/nginx.Dockerfile
          push: true
          tags: clean557/laratm-nginx:${{ github.run_number }}

  deployment:
    needs: build
    environment: staging
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USERNAME}}
          password: ${{ secrets.SERVER_SSH_PRIVATE_KEY}}
          port: ${{ secrets.SERVER_PORT}}
          script: |
            whoami
            export IMAGE_VER=${{ github.run_number }}
            mkdir -p ~/laratm
            cd ~/laratm
            git clone https://github.com/ikrar557/K3-Simple-Laravel-HW6.git .
            git checkout -b balance-feature
            docker-compose build
            docker-compose up -d

